### ISSUE TITLE
extractFileToDisk is creating directory structure but files are not written.

### ISSUE THREAD

**Issue by busslina** [brendan-duncan/archive#228]
Files are created but not written, so all files are 0 bytes length. I will try to use extractArchiveToDisk to see if works better

**Comment by busslina** [comment]
Seems to be big bugs to be resolved and some functionality to be added (maintain permissions).

Does anyone knows a better unzipper package for Dart?. This package is great, but use it force me to bypass these issue by adding tricky code

**Comment by brendan-duncan** [comment]
Are you using the latest version of the archive package, 3.3.5? There was a recent bug that with that which was fixed in the latest version.

**Comment by busslina** [comment]
You are right. I'm using 3.3.4. But is weird, I normally don't specify package versions on pubspec.yaml, because I installed it yesterday. I will test and comment the results. Thanks

**Comment by busslina** [comment]
extractArchiveToDisk  tested with version 3.3.5 and now works writting file content. Still not preserving file permissions.
